# Generated by Django 3.0.3 on 2020-06-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_popuate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.FloatField(null=True)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Confirmed', models.FloatField(null=True)),
                ('Recovered', models.FloatField(null=True)),
                ('Deaths', models.FloatField(null=True)),
            ],
        ),
    ]
